### PR TITLE
Better error message when running tests without redis

### LINKED ISSUE #143: cargo test failing on master branch
Here's the output of `cargo test` on master on my machine, with backtrace:
```
⌁ RUST_BACKTRACE=1 cargo test
    Finished dev [unoptimized + debuginfo] target(s) in 0.24s
     Running target/debug/deps/interledger-9f3b91b8d16f1e88

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/interledger-6889c38a723e4d11

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/btp_end_to_end-cc2d1100eaf339f0

running 1 test
test btp_end_to_end ... FAILED

failures:

---- btp_end_to_end stdout ----
thread 'btp_end_to_end' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:999:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:208
   4: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: std::panicking::try::do_call
             at src/libstd/panicking.rs:308
   7: <T as core::any::Any>::type_id
             at src/libcore/panicking.rs:85
   8: mio::sys::unix::dlsym::fetch
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libcore/macros.rs:18
   9: core::result::Result<T,E>::unwrap
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libcore/result.rs:800
  10: btp_end_to_end::redis_helpers::RedisServer::new
             at crates/interledger/tests/redis_helpers.rs:106
  11: btp_end_to_end::redis_helpers::TestContext::new
             at crates/interledger/tests/redis_helpers.rs:146
  12: btp_end_to_end::btp_end_to_end
             at crates/interledger/tests/btp_end_to_end.rs:24
  13: btp_end_to_end::btp_end_to_end::{{closure}}
             at crates/interledger/tests/btp_end_to_end.rs:22
  14: core::ops::function::FnOnce::call_once
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libcore/ops/function.rs:231
  15: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/liballoc/boxed.rs:704
  16: panic_unwind::dwarf::eh::read_encoded_pointer
             at src/libpanic_unwind/lib.rs:85
  17: test::run_test::run_test_inner::{{closure}}
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/panicking.rs:272
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/panic.rs:394
             at src/libtest/lib.rs:1468


failures:
    btp_end_to_end

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '-p interledger --test btp_end_to_end'
```

### PR DESCRIPTION
**Pull request by bstrie**
Fixes #143.

Secretly this PR is also intended to test whether or not CI is set up to look for new dependencies automatically, since a new patch version of crossbeam (which we transitively depend on) has been released to address an objection by cargo-audit, which we gate our CI on and which would previously cause PRs to be rejected spuriously. I assume this is the case, unless CI is trying to do some sneaky caching or something.

### CODE REVIEW

File: crates/interledger/tests/redis_helpers.rs [hunk 1]
```diff
@@ -99,7 +99,15 @@ impl RedisServer {
             }
         };
 
-        let process = cmd.spawn().unwrap();
+        let process = match cmd.spawn() {
```
Comment (emschwartz) [inline crates/interledger/tests/redis_helpers.rs]: nit: this match statement could be simplified by replacing the `unwrap` with an `expect`

Comment (bstrie) [reply crates/interledger/tests/redis_helpers.rs]: Heh, I originally justified the explicit panic by doing something fancier with the error message, only to eventually settle on a style that essentially mirrors what expect gives anyway. :P

**Comment by emschwartz** [comment]
@bstrie you can merge this as soon as you rebase it on the latest master
